# Generated by Django 2.1.4 on 2019-01-06 01:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebResources', '0003_netresource_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebResources.OriginalCategory')),
            ],
        ),
    ]
